src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
class Trick
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTime $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $modified_at = null;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Image::class)]
    private Collection $images;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Video::class)]
    private Collection $videos;

    #[ORM\ManyToOne(inversedBy: 'tricks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'tricks')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTime
    {
        return $this->modified_at;
    }

    public function setModifiedAt(?\DateTime $modified_at): self
    {
        $this->modified_at = $modified_at;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>
    {% block title %}
    Welcome!
    {% endblock %}
  </title>
  <link rel="icon"
    href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
    integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" />
  <link rel="stylesheet" href="{{ asset('css/style.css') }}" />
  {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
  {% block stylesheets %}
  {{ encore_entry_link_tags('app') }}
  {% endblock %}

  {% block javascripts %}
  {{ encore_entry_script_tags('app') }}
  {% endblock %}
</head>

<body>
  {% include 'navbar.html.twig' %}
  {% block body %}{% endblock %}
  {% include 'footer.html.twig' %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
  <script src="{{ asset('js/navbar.js') }}"></script>
</body>

</html>

templates/footer.html.twig
<footer class="py-4 border-top">
  <div class="container">
    <div class="d-flex justify-content-between">
      <span class="text-muted pt-1">&copy; 2022 Company, Inc</span>
      <div>
        <a class="text-muted" href="#"><i class="fa-brands fa-twitter fs-2"></i></a>
        <a class="text-muted ms-2 ms-md-3" href="#"><i class="fa-brands fa-instagram fs-2"></i></a>
        <a class="text-muted ms-2 ms-md-3" href="#"><i class="fa-brands fa-facebook fs-2"></i></a>
      </div>
    </div>
  </div>
</footer>

templates/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Home
{% endblock %}

{% block body %}
<main>
  <div class="px-4 py-5 mb-5 text-center hero">
    {# <h1 class="display-5 fw-bold">Centered hero</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most
        popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive
        prebuilt components, and powerful JavaScript plugins.</p> #}
      <div class="position-absolute bottom-0 start-50 pb-4">
        <a href="#tricks"><i class="fa-solid fa-circle-chevron-down fs-1 herobtn"></i></a>
      </div>
    </div>
  </div>
  <div>
    <div class="container" id="tricks">
      <div class="mb-4">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 g-4 mb-4">
          {% for trick in tricks %}
          <div class="col">
            <div class="card">
              <img class="img-fluid" src="https://dummyimage.com/388x258/dee1e6/697379.jpg" alt="..." />
              <div class="card-body d-flex justify-content-between p-2">
                <a class="text-decoration-none text-dark" href="{{ path('app_trick', {id:trick.id}) }}">
                  <h5 class="card-title fs-6 text-uppercase">{{ trick.name }}</h5>
                </a>
                <div>
                  <a href="" class="text-decoration-none fa-sharp fa-solid fa-pen"></a>
                  <a href="" class="text-decoration-none fa-solid fa-trash-can ms-2"></a>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="text-center">
          <a href=""><i class="fa-solid fa-circle-plus fs-1"></i></a>
        </div>
      </div>
    </div>
    <div class="sticky-bottom float-end d-none d-xl-block mt-3 pe-3 pb-3">
      <a href="#tricks"><i class="fa-solid fa-circle-chevron-up fs-1"></i></a>
    </div>
  </div>
</main>
{% endblock %}

templates/navbar.html.twig
<header>
  <nav class="navbar navbar-expand-sm fixed-top" aria-label="Third navbar example">
    <div class="container">
      <a href="#"><img class="logo" src="../img/snowtricks-logo.svg" alt="" /></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"
        aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation"><span
          class="navbar-toggler-icon"></span></button>

      <div class="collapse navbar-collapse justify-content-end" id="navbar">
        <ul class="navbar-nav mb-2 mb-sm-0">
          <li class="nav-item">
            <a href="{{ path('app_homepage') }}" class="nav-link fw-semibold" aria-current="page">Home</a>
          </li>
          <li class="nav-item">
            <a href="#tricks" class="nav-link fw-semibold">Tricks</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link fw-semibold" data-bs-toggle="modal" data-bs-target="#modal">Sign-in</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link fw-semibold" data-bs-toggle="modal" data-bs-target="#modal">Sign-up</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title " id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

        <div class="modal-footer py-3">
        </div>
      </div>
    </div>
  </div>
</div>

templates/trick.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Trick
{% endblock %}

{% block body %}
<main class="offset">
  <div class="container">
    <div class="mb-4 position-relative">
      <img class="w-100 rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." />
      <h1 class="position-absolute bottom-0 start-50 translate-middle text-uppercase fs-1">{{ trick.name }}</h1>
      <div class="position-absolute top-0 end-0 py-3">
        <a href="" class="text-decoration-none fa-sharp fa-solid fa-pen"></a>
        <a href="" class="text-decoration-none fa-solid fa-trash-can mx-3"></a>
      </div>
    </div>
    <section id="medias" class="mb-4">
      <div class="row">
        <!-- photos -->
        <div class="d-none d-lg-block col-6">
          <div id="carousel1" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="row">
                  {% for i in 1..3 %}
                  <div class="col-lg-4">
                    <div class="card">
                      <img class="d-block w-100" src="https://dummyimage.com/388x258/dee1e6/697379.jpg" alt="..." />
                      <div class="card-body text-end p-2">
                        <a href="" class="text-decoration-none fa-sharp fa-solid fa-pen"></a>
                        <a href="" class="text-decoration-none fa-solid fa-trash-can mx-2"></a>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
              <div class="carousel-item">
                <div class="row">
                  {% for i in 1..3 %}
                  <div class="col-lg-4">
                    <div class="card">
                      <img class="d-block w-100" src="https://dummyimage.com/388x258/dee1e6/697379.jpg" alt="..." />
                      <div class="card-body text-end p-2">
                        <a href="" class="text-decoration-none fa-sharp fa-solid fa-pen"></a>
                        <a href="" class="text-decoration-none fa-solid fa-trash-can mx-2"></a>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel1" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel1" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
        <!-- video -->
        <div class="d-none d-lg-block col-6">
          <div id="carousel2" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="row">
                  {% for i in 1..3 %}
                  <div class="col-lg-4">
                    <div class="card">
                      <img class="d-block w-100" src="https://dummyimage.com/388x258/dee1e6/697379.jpg" alt="..." />
                      <div class="card-body text-end p-2">
                        <a href="" class="text-decoration-none fa-sharp fa-solid fa-pen"></a>
                        <a href="" class="text-decoration-none fa-solid fa-trash-can mx-2"></a>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
              <div class="carousel-item">
                <div class="row">
                  {% for i in 1..3 %}
                  <div class="col-lg-4">
                    <div class="card">
                      <img class="d-block w-100" src="https://dummyimage.com/388x258/dee1e6/697379.jpg" alt="..." />
                      <div class="card-body text-end p-2">
                        <a href="" class="text-decoration-none fa-sharp fa-solid fa-pen"></a>
                        <a href="" class="text-decoration-none fa-solid fa-trash-can mx-2"></a>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel2" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel2" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
      </div>
      <div class="text-center">
        <button class="btn btn-primary d-lg-none">Medias</button>
      </div>
    </section>
    <section id="description">
      <div class="col-md-10 mx-auto">
        <div class="mb-3">
          <img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />
          <span class="fw-bold">username</span>
        </div>
        <div>
          <p class="text-muted fst-italic">publié le {{ trick.createdAt|date('d/m/Y') }}</p>
          {% if trick.modifiedAt %}
          <p class="text-muted fst-italic">mis à jour le {{ trick.modifiedAt|date('d/m/Y') }} </p>
          {% endif %}
        </div>
        <a class="badge bg-secondary text-decoration-none mb-3" href="#!">Groupe</a>
        <p>{{ trick.description }}</p>
      </div>
    </section>
    <!-- Comments section -->
    <section class="mb-5">
      <div class="card col-md-10 mx-auto bg-light">
        <div class="card-body">
          <!-- Comment form -->
          <form class="mb-4">
            <textarea class="form-control mb-3" rows="3"
              placeholder="Join the discussion and leave a comment!"></textarea>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">Valider</button>
            </div>
          </form>
          <!-- Comment with nested comments -->
          <div class="d-flex mb-4">
            <!-- Parent comment -->
            <div class="flex-shrink-0">
              <img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />
            </div>
            <div class="ms-3">
              <div class="fw-bold">Commenter Name</div>If you're going to lead a space frontier, it has to be
              government; it'll never be private enterprise. Because the space frontier is dangerous, and it's
              expensive, and it has unquantified risks.
              <!-- Child comment 1 -->
              <div class="d-flex mt-4">
                <div class="flex-shrink-0">
                  <img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />
                </div>
                <div class="ms-3">
                  <div class="fw-bold">Commenter Name</div>And under those conditions, you cannot establish a
                  capital-market evaluation of that enterprise. You can't get investors.
                </div>
              </div>
              <!-- Child comment 2 -->
              <div class="d-flex mt-4">
                <div class="flex-shrink-0">
                  <img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />
                </div>
                <div class="ms-3">
                  <div class="fw-bold">Commenter Name</div>When you put money directly to a problem, it makes a good
                  headline.
                </div>
              </div>
            </div>
          </div>
          <!-- Single comment -->
          <div class="d-flex">
            <div class="flex-shrink-0">
              <img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />
            </div>
            <div class="ms-3">
              <div class="fw-bold">Commenter Name</div>When I look at the universe and all the ways the universe wants
              to kill us, I find it hard to reconcile that with statements of beneficence.
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</main>
{% endblock %}